spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dummy
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: app_db
  sql:
    init:
      mode: always
flyway:
  baseline-on-migrate: true
  baseline-version: 0





